# theme       : jekyll-theme-slate
title       : "NDS Flashcart Index"
description : "An index of all Nintendo DS flashcarts"
repo        : "flashcarts/nds-index"
color       : "#80158A"
image       : "/assets/images/favicon/favicon-196x196.png"

sass:
  sass_dir: _sass

exclude:
  - Gemfile*
  - vendor
  - LICENSE*

analytics:
  gtag:
    id: G-Z9LJ9NMQCQ
    anonymize_ip: true # false (default)

defaults:
  - scope:
      path: "**/*.md"
    values:
      layout: app

collections:
  card:
    output: true
