# theme       : jekyll-theme-slate
title       : "NDS Flashcard Index"
description : "An index of all Nintendo DS flashcards"
repo        : "flashcarts/nds-index"
color       : "#80158A"
image       : "/assets/images/favicon/favicon-196x196.png"

sass:
  sass_dir: _sass

defaults:
  - scope:
      path: "**/*.md"
    values:
      layout: app

collections:
  card:
    output: true
