# theme       : jekyll-theme-slate
title       : "Kernel Themes"
description : "A repository for flashcart kernel themes"
repo        : "Sanrax/kernel-themes"
color       : "#80158A"
image       : "/assets/images/favicon/favicon-196x196.png"

sass:
  sass_dir: _sass

exclude:
  - Gemfile*
  - vendor
  - LICENSE*

defaults:
  - scope:
      path: "**/*.md"
    values:
      layout: app

collections:
  akmenu:
    output: true
